#!/bin/bash

# 🎯 Tank Royale 2 - Quick Command Reference
# Run this to see all available commands

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║         Tank Royale 2 - Quick Command Reference               ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📦 CONTAINER MANAGEMENT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ./tank.sh setup        🚀 First time setup (creates everything)"
echo "  ./tank.sh start        ▶️  Start all existing containers"
echo "  ./tank.sh stop         ⏹️  Stop all containers (keeps data)"
echo "  ./tank.sh databases    🗄️  Start databases only"
echo "  ./tank.sh monitoring   📊 Start monitoring only"
echo "  ./tank.sh help         ❓ Show this help"
echo ""
echo "🔍 CONTAINER STATUS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  podman ps                        List running containers"
echo "  podman ps -a                     List all containers"
echo "  podman logs -f tank-<service>    Follow container logs"
echo "  podman stats                     Resource usage"
echo ""
echo "🚀 APPLICATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  cd server && npm run dev         Start API server"
echo "  cd game-server && npm run dev    Start game server"
echo "  curl http://localhost:3000/health  Health check"
echo ""
echo "🧪 LOAD TESTING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  cd load-tests && npm run setup   Create test users"
echo "  cd load-tests && npm run test:quick   Quick test (5 clients)"
echo "  cd load-tests && npm run test:all     All tests"
echo ""
echo "🌐 SERVICE URLS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Grafana:        http://localhost:3001  (admin/admin123)"
echo "  Prometheus:     http://localhost:9090"
echo "  pgAdmin:        http://localhost:8080  (admin@tankroyale.com/admin123)"
echo "  Redis Commander: http://localhost:8081"
echo "  Server Metrics: http://localhost:3000/metrics"
echo ""
echo "📚 DOCUMENTATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  GETTING_STARTED.md      Quick start guide"
echo "  CONTAINER_SCRIPTS.md    Complete script documentation"
echo "  LOAD_TESTING_SETUP.md   Load testing guide"
echo "  docs/ARCHITECTURE.md    System architecture"
echo ""
echo "🗑️ CLEANUP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  podman compose down              Stop & remove containers"
echo "  podman compose down -v           ⚠️  Delete everything + data"
echo "  podman system prune -a --volumes  ⚠️  Clean all unused resources"
echo ""
echo "💡 TIP: Run './tank.sh start' for daily development!"
echo "💡 All scripts are in the ./scripts/ folder"
echo ""
